#默认首页地址：http://localhost:8080/backend/page/login/login.html
server:
  port: 8080
spring:
  application:
    #应用名称，可选项，不配置默认使用工程名1112222
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #数据库表中命名规则通常使用下划线，Java类通常使用驼峰命名 address_book-->AddressBook  user_name-->userName
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键生成策略
      id-type: ASSIGN_ID

reggie:
  path: D:\